name: Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version Check
        id: version_check
        run: |
          latest=$(curl -f -s "https://api.bfdibranches.com/version.php")
          if [ -f unrelated/version.txt ]; then
            current=$(cat unrelated/version.txt)
          else
            current="blehh :P"
          fi
          if [ -z "$latest" ]; then
            echo "Could not get version."
            exit 1
          fi
          if [ "$latest" != "$current" ]; then
            echo "$latest" > unrelated/version.txt
            echo "new=true" >> $GITHUB_ENV
            echo "releaseTag=v$latest" >> $GITHUB_ENV
          else
            echo "Up to date."
            exit 0 # why did i put that there below
            #echo "new=false" >> $GITHUB_ENV
          fi

      - name: Commit
        if: env.new == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add unrelated/version.txt
          git commit -m "update version [skip ci]"
          git push

      - name: Zippy
        if: env.new == 'true'
        run: |
            chmod +x lazykazy.sh
            ./lazykazy.sh
      
      - name: Make Release
        if: env.new == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.releaseTag }}
          body: A version of BFDI Branches.
          files: branches.zip
